# Generated by Django 5.1.3 on 2024-11-11 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_app', '0003_remove_orderitem_order_remove_orderitem_menuitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('tip', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(default='I', max_length=1)),
                ('size', models.IntegerField(default=12)),
                ('sweetness', models.IntegerField(default=0)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('menuitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tea_app.menuitem')),
                ('milk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tea_app.milk')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='tea_app.order')),
            ],
            options={
                'unique_together': {('order', 'menuitem', 'milk', 'temperature', 'size', 'sweetness')},
            },
        ),
    ]
